# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findfriends', '0002_auto_20170103_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
