# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findfriends', '0003_auto_20170103_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='findfriends.TwitterUser'),
        ),
    ]
