# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findfriends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='friends',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='friends',
            field=models.ManyToManyField(related_name='_twitteruser_friends_+', to='findfriends.TwitterUser'),
        ),
    ]
